services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: meli_backend
        ports:
            - "3000:3000"
        volumes:
            - ./backend:/app
            - /app/node_modules
        environment:
            NODE_ENV: development
            TEMPO_URL: "http://tempo:4318"
        restart: unless-stopped
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: meli_frontend
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            NODE_ENV: development
            VITE_API_URL: http://backend:3000
        restart: unless-stopped
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
